### ISSUE TITLE
We don't have a dataset

### ISSUE THREAD

**Issue by dsanmart** [dsanmart/everywhere-reco#1]

**Comment by dsanmart** [comment]
Connected on Linkedin with Javier Perez (CTO @ Fourvenues), Alejandro Joshua (Software Developer @ Fourvenues), and Pedro Perez (Founder Guru It!) to propose a partnership where we develop the system for their applications.

**Comment by pabloortegaa** [comment]
I found a rich dataset with 15k examples. It is divided into 5 csv files, which makes the dataset richer. Also, there is a test dataset with which we can test the different models.
