### ISSUE TITLE
problems uploading the dataset

### ISSUE THREAD

**Issue by pabloortegaa** [dsanmart/everywhere-reco#2]
I am having problems with the dataset EVEnts because it is a 1GB file. Should we have all the files in Google Drive/One drive and make a request each time we want to import the dataset? Is that possible?

**Comment by dsanmart** [comment]
We can upload up to 2GB for free using [git-lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github). I suggest we use this at least for the training dataset and if the data that exceeds 2GB we can also just share it between the team through drive and keep it in local using .gitignore
