### ISSUE TITLE
Feedback iteration 2

### ISSUE THREAD

**Issue by miguelgfierro** [dsanmart/everywhere-reco#7]
- [x] It is a good practice to have all the imports at the top of the notebook instead of in between because if there is a missing library, you will detect it at the beginning.
- [x] Work in different branches and for every new small feature, do a PR to main

**Comment by rayanmazari90** [comment]
Hi Sir @miguelgfierro,

Issue 1: Imports not organized properly
Closed: Issue resolved


Thanks for bringing this issue to our attention. We have made the necessary changes and now all the libraries are imported at the top of the notebook. This should make it easier to detect any missing libraries at the beginning. The latest commit includes these changes.

Issue 2: Branching and Pull Request workflow
Label: enhancement


Thank you for your valuable suggestion on improving our project workflow. We completely agree that working in different branches and creating Pull Requests (PRs) for every new feature is a good practice. This will not only improve the overall code quality but also make the project more maintainable.

We will incorporate this advice for future improvement of the project's components and ensure that the team follows the recommended branching and PR workflow. We appreciate your input and will keep this issue open to track our progress on this enhancement.

Thanks again for your advices to our project!

**Comment by rayanmazari90** [comment]
Hi Sir @miguelgfierro,

Issue 1: Imports not organized properly
Closed: Issue resolved

Thanks for bringing this issue to our attention. We have made the necessary changes and now all the libraries are imported at the top of the notebook. This should make it easier to detect any missing libraries at the beginning. The latest commit includes these changes.

Issue 2: Branching and Pull Request workflow
Label: enhancement

Thank you for your valuable suggestion on improving our project workflow. We completely agree that working in different branches and creating Pull Requests (PRs) for every new feature is a good practice. This will not only improve the overall code quality but also make the project more maintainable.

We will incorporate this advice for future improvement of the project's components and ensure that the team follows the recommended branching and PR workflow. We appreciate your input and will keep this issue open to track our progress on this enhancement.

Thanks again for your advices to our project!
